//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSAutomationWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSAutomationWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AddRow_16x_24 {
            get {
                object obj = ResourceManager.GetObject("AddRow_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!-- This file was generated by the AiToXaml tool.--&gt;
        ///&lt;!-- Tool Version: 14.0.22307.0 --&gt;
        ///&lt;Viewbox Width=&quot;16&quot; Height=&quot;16&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///  &lt;Rectangle Width=&quot;16&quot; Height=&quot;16&quot;&gt;
        ///    &lt;Rectangle.Fill&gt;
        ///      &lt;DrawingBrush&gt;
        ///        &lt;DrawingBrush.Drawing&gt;
        ///          &lt;DrawingGroup&gt;
        ///            &lt;DrawingGroup.Children&gt;
        ///              &lt;GeometryDrawing Brush=&quot;#00FFFFFF&quot; Geometry=&quot;F1M16,16L0,16 0,0 16,0z&quot; /&gt;
        ///              &lt;GeometryDrawing Brush=&quot;#FFF6F6F6&quot; Geomet [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddRowToAbove_16x {
            get {
                return ResourceManager.GetString("AddRowToAbove_16x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!-- This file was generated by the AiToXaml tool.--&gt;
        ///&lt;!-- Tool Version: 14.0.22307.0 --&gt;
        ///&lt;Viewbox Width=&quot;16&quot; Height=&quot;16&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///  &lt;Rectangle Width=&quot;16&quot; Height=&quot;16&quot;&gt;
        ///    &lt;Rectangle.Fill&gt;
        ///      &lt;DrawingBrush&gt;
        ///        &lt;DrawingBrush.Drawing&gt;
        ///          &lt;DrawingGroup&gt;
        ///            &lt;DrawingGroup.Children&gt;
        ///              &lt;GeometryDrawing Brush=&quot;#00FFFFFF&quot; Geometry=&quot;F1M16,16L0,16 0,0 16,0z&quot; /&gt;
        ///              &lt;GeometryDrawing Brush=&quot;#FFF6F6F6&quot; Geomet [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddRowToBelow_16x {
            get {
                return ResourceManager.GetString("AddRowToBelow_16x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DeleteCommandColumn_ActionGray_16x_24 {
            get {
                object obj = ResourceManager.GetObject("DeleteCommandColumn_ActionGray_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap EditFieldDialog_16x_24 {
            get {
                object obj = ResourceManager.GetObject("EditFieldDialog_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap OpenFolder_16x_24 {
            get {
                object obj = ResourceManager.GetObject("OpenFolder_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Paste_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Paste_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Run_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Run_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Save_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
